In [2]:
import torch

1. Create tensor a from a list (range(9)). Predict and then check the size, offset and stride of a.

a) Create a new tensor using b=a.view(3, 3). What does view do? Check that a and b share the same storage.

b) Create a tensor c =b[1:,1:]. Predict and then check the size, offset and stride of c.

In [41]:
a = torch.tensor(range(9))
print(a.size())
print(a.storage_offset())
print(a.stride())

torch.Size([9])
0
(1,)


In [42]:
b=a.view(3,3)

Explanations: b and c are views of a. b is a formatted version of the original tensor a. c is a indexed view of b. The stride is (3,1), because the original storage is still 9. To get from 4 to 7, you have to go three steps (4 -> 5, 5 -> 6, 6 -> 7), because the 6 is still in the storage, even though it is not in the view.

In [43]:
c = b[1:,1:]
print(c)
print(c.size())
print(c.storage_offset())
print(c.stride())

tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)


2) Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch librarary? 

a) Apply the cuntion element-wise to a. Why does it return an error?

b) What operation is required to make the function work?

c) Is there a version of your function that operates in place?

In [44]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [48]:
torch.sqrt(a.float())

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [50]:
a = a.float()
torch.sqrt_(a)
a

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])